-- ===========================================================================
-- Phase 2: per-user data isolation — add user_id to every tenant table.
-- Backfill sets existing rows to the OWNER user so current data stays visible
-- to you after enabling MULTI_USER_ISOLATED. Replace :owner_id below first.
-- ===========================================================================

ALTER TABLE IF EXISTS public.apartment_documents ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS apartment_documents_user_idx ON public.apartment_documents (user_id);
ALTER TABLE IF EXISTS public.apartment_tenants ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS apartment_tenants_user_idx ON public.apartment_tenants (user_id);
ALTER TABLE IF EXISTS public.apartment_units ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS apartment_units_user_idx ON public.apartment_units (user_id);
ALTER TABLE IF EXISTS public.app_settings ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS app_settings_user_idx ON public.app_settings (user_id);
ALTER TABLE IF EXISTS public.bond_payment_status ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS bond_payment_status_user_idx ON public.bond_payment_status (user_id);
ALTER TABLE IF EXISTS public.bonds ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS bonds_user_idx ON public.bonds (user_id);
ALTER TABLE IF EXISTS public.brokerage_accounts ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS brokerage_accounts_user_idx ON public.brokerage_accounts (user_id);
ALTER TABLE IF EXISTS public.built_documents ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS built_documents_user_idx ON public.built_documents (user_id);
ALTER TABLE IF EXISTS public.built_properties ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS built_properties_user_idx ON public.built_properties (user_id);
ALTER TABLE IF EXISTS public.cash_funds ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS cash_funds_user_idx ON public.cash_funds (user_id);
ALTER TABLE IF EXISTS public.covered_call_positions ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS covered_call_positions_user_idx ON public.covered_call_positions (user_id);
ALTER TABLE IF EXISTS public.dividend_collected ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS dividend_collected_user_idx ON public.dividend_collected (user_id);
ALTER TABLE IF EXISTS public.dividend_tds ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS dividend_tds_user_idx ON public.dividend_tds (user_id);
ALTER TABLE IF EXISTS public.document_folders ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS document_folders_user_idx ON public.document_folders (user_id);
ALTER TABLE IF EXISTS public.expenses ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS expenses_user_idx ON public.expenses (user_id);
ALTER TABLE IF EXISTS public.family_members ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS family_members_user_idx ON public.family_members (user_id);
ALTER TABLE IF EXISTS public.fd_deposits ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS fd_deposits_user_idx ON public.fd_deposits (user_id);
ALTER TABLE IF EXISTS public.fno_accounts ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS fno_accounts_user_idx ON public.fno_accounts (user_id);
ALTER TABLE IF EXISTS public.fno_daily_pnl ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS fno_daily_pnl_user_idx ON public.fno_daily_pnl (user_id);
ALTER TABLE IF EXISTS public.fno_pnl_snapshots ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS fno_pnl_snapshots_user_idx ON public.fno_pnl_snapshots (user_id);
ALTER TABLE IF EXISTS public.fno_trades ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS fno_trades_user_idx ON public.fno_trades (user_id);
ALTER TABLE IF EXISTS public.gold_documents ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS gold_documents_user_idx ON public.gold_documents (user_id);
ALTER TABLE IF EXISTS public.gold_items ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS gold_items_user_idx ON public.gold_items (user_id);
ALTER TABLE IF EXISTS public.hedge_positions ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS hedge_positions_user_idx ON public.hedge_positions (user_id);
ALTER TABLE IF EXISTS public.income_receipts ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS income_receipts_user_idx ON public.income_receipts (user_id);
ALTER TABLE IF EXISTS public.land_documents ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS land_documents_user_idx ON public.land_documents (user_id);
ALTER TABLE IF EXISTS public.land_parcels ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS land_parcels_user_idx ON public.land_parcels (user_id);
ALTER TABLE IF EXISTS public.loan_payment_status ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS loan_payment_status_user_idx ON public.loan_payment_status (user_id);
ALTER TABLE IF EXISTS public.loans ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS loans_user_idx ON public.loans (user_id);
ALTER TABLE IF EXISTS public.option_strategy_bookings ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS option_strategy_bookings_user_idx ON public.option_strategy_bookings (user_id);
ALTER TABLE IF EXISTS public.option_strategy_legs ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS option_strategy_legs_user_idx ON public.option_strategy_legs (user_id);
ALTER TABLE IF EXISTS public.option_strategy_snapshots ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS option_strategy_snapshots_user_idx ON public.option_strategy_snapshots (user_id);
ALTER TABLE IF EXISTS public.option_strategy_trades ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS option_strategy_trades_user_idx ON public.option_strategy_trades (user_id);
ALTER TABLE IF EXISTS public.other_income ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS other_income_user_idx ON public.other_income (user_id);
ALTER TABLE IF EXISTS public.portfolio_screener_links ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS portfolio_screener_links_user_idx ON public.portfolio_screener_links (user_id);
ALTER TABLE IF EXISTS public.purchase_wishlist ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS purchase_wishlist_user_idx ON public.purchase_wishlist (user_id);
ALTER TABLE IF EXISTS public.reminder_overrides ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS reminder_overrides_user_idx ON public.reminder_overrides (user_id);
ALTER TABLE IF EXISTS public.salary_entries ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS salary_entries_user_idx ON public.salary_entries (user_id);
ALTER TABLE IF EXISTS public.stock_accounts ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS stock_accounts_user_idx ON public.stock_accounts (user_id);
ALTER TABLE IF EXISTS public.stock_dividend_meta ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS stock_dividend_meta_user_idx ON public.stock_dividend_meta (user_id);
ALTER TABLE IF EXISTS public.stock_dividends ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS stock_dividends_user_idx ON public.stock_dividends (user_id);
ALTER TABLE IF EXISTS public.stock_holdings ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS stock_holdings_user_idx ON public.stock_holdings (user_id);
ALTER TABLE IF EXISTS public.stock_trades ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS stock_trades_user_idx ON public.stock_trades (user_id);
ALTER TABLE IF EXISTS public.ulip_policies ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS ulip_policies_user_idx ON public.ulip_policies (user_id);
ALTER TABLE IF EXISTS public.vault_documents ADD COLUMN IF NOT EXISTS user_id TEXT;
CREATE INDEX IF NOT EXISTS vault_documents_user_idx ON public.vault_documents (user_id);
